//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EnergyMarketPriceTestEntities2 : DbContext
    {
        public EnergyMarketPriceTestEntities2()
            : base("name=EnergyMarketPriceTestEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        [DbFunction("EnergyMarketPriceTestEntities2", "fnFormulaByKey")]
        public virtual IQueryable<fnFormulaByKey_Result> fnFormulaByKey(string key)
        {
            var keyParameter = key != null ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnFormulaByKey_Result>("[EnergyMarketPriceTestEntities2].[fnFormulaByKey](@Key)", keyParameter);
        }
    
        [DbFunction("EnergyMarketPriceTestEntities2", "fnFormulaVPC")]
        public virtual IQueryable<fnFormulaVPC_Result> fnFormulaVPC(Nullable<int> formula)
        {
            var formulaParameter = formula.HasValue ?
                new ObjectParameter("Formula", formula) :
                new ObjectParameter("Formula", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnFormulaVPC_Result>("[EnergyMarketPriceTestEntities2].[fnFormulaVPC](@Formula)", formulaParameter);
        }
    }
}
