//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EnergyMarketPriceTestEntities : DbContext
    {
        public EnergyMarketPriceTestEntities()
            : base("name=EnergyMarketPriceTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Formula> Formulae { get; set; }
    
        [DbFunction("EnergyMarketPriceTestEntities", "fnFormulaVPC")]
        public virtual IQueryable<fnFormulaVPC_Result> fnFormulaVPC(Nullable<int> formula)
        {
            var formulaParameter = formula.HasValue ?
                new ObjectParameter("Formula", formula) :
                new ObjectParameter("Formula", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnFormulaVPC_Result>("[EnergyMarketPriceTestEntities].[fnFormulaVPC](@Formula)", formulaParameter);
        }
    }
}
