//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodafone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFormulaVPC
    {
        public int ID { get; set; }
        public Nullable<int> Formula { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<double> SumMarket_Value { get; set; }
        public Nullable<double> StdevMarket_Value { get; set; }
        public Nullable<double> AnualMarket_Value { get; set; }
        public Nullable<double> MaxPriceFixed { get; set; }
        public Nullable<decimal> VolumeFixProcent { get; set; }
        public Nullable<decimal> VolumeTotal { get; set; }
        public string Indicator { get; set; }
        public Nullable<System.DateTime> MinMarket_Date { get; set; }
        public Nullable<double> MinMarket_Value { get; set; }
        public Nullable<double> High { get; set; }
        public Nullable<double> Medium { get; set; }
        public Nullable<double> Low { get; set; }
    }
}
